# Site settings
title: 'Políticas Públicas' # Your Title
tagline: 'Twisted tales to make you shudder' # A brief tagline for your site
sidebar_image: /images/cover.jpg

# Build settings
markdown: kramdown
highlighter: pygments
baseurl: /strange_case # the subpath of your site, e.g. /blog/
